name: Generate Snake Animation

on:
  push:
    branches:
      - master  # Adjust this if your default branch is not "master"
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight

jobs:
  generate:
    name: Generate Snake
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: emiroow
          output: dist/github-contribution-grid-snake.svg

      - name: Upload Snake Animation
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/github-contribution-grid-snake.svg

  update:
    name: Commit and Push Snake
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Snake Animation
        uses: actions/download-artifact@v3
        with:
          name: snake-animation
          path: dist/

      - name: Commit and Push Changes
        run: |
          mv dist/github-contribution-grid-snake.svg ./github-contribution-grid-snake.svg
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add github-contribution-grid-snake.svg
          git commit -m "Update Snake Animation"
          git push
